/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterAddParticipantRouteImport } from './routes/register/add-participant'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as Admin403RouteImport } from './routes/admin/403'
import { Route as AbsensiFormIdRouteImport } from './routes/absensi/$formId'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AdminSettingsRouteRouteImport } from './routes/admin/settings/route'
import { Route as AdminLupgRouteRouteImport } from './routes/admin/lupg/route'
import { Route as AdminTasksIndexRouteImport } from './routes/admin/tasks/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminParticipantsIndexRouteImport } from './routes/admin/participants/index'
import { Route as AdminManageRoleIndexRouteImport } from './routes/admin/manage-role/index'
import { Route as AdminHelpCenterIndexRouteImport } from './routes/admin/help-center/index'
import { Route as AdminFormsIndexRouteImport } from './routes/admin/forms/index'
import { Route as AdminChatsIndexRouteImport } from './routes/admin/chats/index'
import { Route as AdminAttendanceIndexRouteImport } from './routes/admin/attendance/index'
import { Route as AdminAppsIndexRouteImport } from './routes/admin/apps/index'
import { Route as AdminApprovalsIndexRouteImport } from './routes/admin/approvals/index'
import { Route as AdminSettingsNotificationsRouteImport } from './routes/admin/settings/notifications'
import { Route as AdminSettingsAppearanceRouteImport } from './routes/admin/settings/appearance'
import { Route as AdminSettingsAccountRouteImport } from './routes/admin/settings/account'
import { Route as AdminLupgDashboardRouteImport } from './routes/admin/lupg/dashboard'
import { Route as AdminFormsCreateRouteImport } from './routes/admin/forms/create'
import { Route as AdminErrorsErrorRouteImport } from './routes/admin/errors/$error'
import { Route as AdminLupgSensusIndexRouteImport } from './routes/admin/lupg/sensus/index'
import { Route as AdminLupgReportsIndexRouteImport } from './routes/admin/lupg/reports/index'
import { Route as AdminLupgRecapIndexRouteImport } from './routes/admin/lupg/recap/index'
import { Route as AdminLupgProgramsIndexRouteImport } from './routes/admin/lupg/programs/index'
import { Route as AdminLupgPresentationIndexRouteImport } from './routes/admin/lupg/presentation/index'
import { Route as AdminLupgMustinIndexRouteImport } from './routes/admin/lupg/mustin/index'
import { Route as AdminLupgConfigIndexRouteImport } from './routes/admin/lupg/config/index'
import { Route as AdminLupgReportsMonthlyReportIdRouteImport } from './routes/admin/lupg/reports/$monthlyReportId'
import { Route as AdminLupgRecapPresentRouteImport } from './routes/admin/lupg/recap/present'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterAddParticipantRoute = RegisterAddParticipantRouteImport.update({
  id: '/register/add-participant',
  path: '/register/add-participant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const Admin403Route = Admin403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AbsensiFormIdRoute = AbsensiFormIdRouteImport.update({
  id: '/absensi/$formId',
  path: '/absensi/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRouteRoute = AdminSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLupgRouteRoute = AdminLupgRouteRouteImport.update({
  id: '/lupg',
  path: '/lupg',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTasksIndexRoute = AdminTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminParticipantsIndexRoute = AdminParticipantsIndexRouteImport.update({
  id: '/participants/',
  path: '/participants/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminManageRoleIndexRoute = AdminManageRoleIndexRouteImport.update({
  id: '/manage-role/',
  path: '/manage-role/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHelpCenterIndexRoute = AdminHelpCenterIndexRouteImport.update({
  id: '/help-center/',
  path: '/help-center/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFormsIndexRoute = AdminFormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminChatsIndexRoute = AdminChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAttendanceIndexRoute = AdminAttendanceIndexRouteImport.update({
  id: '/attendance/',
  path: '/attendance/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAppsIndexRoute = AdminAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminApprovalsIndexRoute = AdminApprovalsIndexRouteImport.update({
  id: '/approvals/',
  path: '/approvals/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsNotificationsRoute =
  AdminSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AdminSettingsRouteRoute,
  } as any)
const AdminSettingsAppearanceRoute = AdminSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminSettingsAccountRoute = AdminSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminSettingsRouteRoute,
} as any)
const AdminLupgDashboardRoute = AdminLupgDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminLupgRouteRoute,
} as any)
const AdminFormsCreateRoute = AdminFormsCreateRouteImport.update({
  id: '/forms/create',
  path: '/forms/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminErrorsErrorRoute = AdminErrorsErrorRouteImport.update({
  id: '/errors/$error',
  path: '/errors/$error',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLupgSensusIndexRoute = AdminLupgSensusIndexRouteImport.update({
  id: '/sensus/',
  path: '/sensus/',
  getParentRoute: () => AdminLupgRouteRoute,
} as any)
const AdminLupgReportsIndexRoute = AdminLupgReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AdminLupgRouteRoute,
} as any)
const AdminLupgRecapIndexRoute = AdminLupgRecapIndexRouteImport.update({
  id: '/recap/',
  path: '/recap/',
  getParentRoute: () => AdminLupgRouteRoute,
} as any)
const AdminLupgProgramsIndexRoute = AdminLupgProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => AdminLupgRouteRoute,
} as any)
const AdminLupgPresentationIndexRoute =
  AdminLupgPresentationIndexRouteImport.update({
    id: '/presentation/',
    path: '/presentation/',
    getParentRoute: () => AdminLupgRouteRoute,
  } as any)
const AdminLupgMustinIndexRoute = AdminLupgMustinIndexRouteImport.update({
  id: '/mustin/',
  path: '/mustin/',
  getParentRoute: () => AdminLupgRouteRoute,
} as any)
const AdminLupgConfigIndexRoute = AdminLupgConfigIndexRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => AdminLupgRouteRoute,
} as any)
const AdminLupgReportsMonthlyReportIdRoute =
  AdminLupgReportsMonthlyReportIdRouteImport.update({
    id: '/reports/$monthlyReportId',
    path: '/reports/$monthlyReportId',
    getParentRoute: () => AdminLupgRouteRoute,
  } as any)
const AdminLupgRecapPresentRoute = AdminLupgRecapPresentRouteImport.update({
  id: '/recap/present',
  path: '/recap/present',
  getParentRoute: () => AdminLupgRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/lupg': typeof AdminLupgRouteRouteWithChildren
  '/admin/settings': typeof AdminSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/absensi/$formId': typeof AbsensiFormIdRoute
  '/admin/403': typeof Admin403Route
  '/admin/dashboard': typeof AdminDashboardRoute
  '/register/add-participant': typeof RegisterAddParticipantRoute
  '/admin/errors/$error': typeof AdminErrorsErrorRoute
  '/admin/forms/create': typeof AdminFormsCreateRoute
  '/admin/lupg/dashboard': typeof AdminLupgDashboardRoute
  '/admin/settings/account': typeof AdminSettingsAccountRoute
  '/admin/settings/appearance': typeof AdminSettingsAppearanceRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/admin/approvals': typeof AdminApprovalsIndexRoute
  '/admin/apps': typeof AdminAppsIndexRoute
  '/admin/attendance': typeof AdminAttendanceIndexRoute
  '/admin/chats': typeof AdminChatsIndexRoute
  '/admin/forms': typeof AdminFormsIndexRoute
  '/admin/help-center': typeof AdminHelpCenterIndexRoute
  '/admin/manage-role': typeof AdminManageRoleIndexRoute
  '/admin/participants': typeof AdminParticipantsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/tasks': typeof AdminTasksIndexRoute
  '/admin/lupg/recap/present': typeof AdminLupgRecapPresentRoute
  '/admin/lupg/reports/$monthlyReportId': typeof AdminLupgReportsMonthlyReportIdRoute
  '/admin/lupg/config': typeof AdminLupgConfigIndexRoute
  '/admin/lupg/mustin': typeof AdminLupgMustinIndexRoute
  '/admin/lupg/presentation': typeof AdminLupgPresentationIndexRoute
  '/admin/lupg/programs': typeof AdminLupgProgramsIndexRoute
  '/admin/lupg/recap': typeof AdminLupgRecapIndexRoute
  '/admin/lupg/reports': typeof AdminLupgReportsIndexRoute
  '/admin/lupg/sensus': typeof AdminLupgSensusIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/lupg': typeof AdminLupgRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/absensi/$formId': typeof AbsensiFormIdRoute
  '/admin/403': typeof Admin403Route
  '/admin/dashboard': typeof AdminDashboardRoute
  '/register/add-participant': typeof RegisterAddParticipantRoute
  '/admin/errors/$error': typeof AdminErrorsErrorRoute
  '/admin/forms/create': typeof AdminFormsCreateRoute
  '/admin/lupg/dashboard': typeof AdminLupgDashboardRoute
  '/admin/settings/account': typeof AdminSettingsAccountRoute
  '/admin/settings/appearance': typeof AdminSettingsAppearanceRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/admin/approvals': typeof AdminApprovalsIndexRoute
  '/admin/apps': typeof AdminAppsIndexRoute
  '/admin/attendance': typeof AdminAttendanceIndexRoute
  '/admin/chats': typeof AdminChatsIndexRoute
  '/admin/forms': typeof AdminFormsIndexRoute
  '/admin/help-center': typeof AdminHelpCenterIndexRoute
  '/admin/manage-role': typeof AdminManageRoleIndexRoute
  '/admin/participants': typeof AdminParticipantsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/tasks': typeof AdminTasksIndexRoute
  '/admin/lupg/recap/present': typeof AdminLupgRecapPresentRoute
  '/admin/lupg/reports/$monthlyReportId': typeof AdminLupgReportsMonthlyReportIdRoute
  '/admin/lupg/config': typeof AdminLupgConfigIndexRoute
  '/admin/lupg/mustin': typeof AdminLupgMustinIndexRoute
  '/admin/lupg/presentation': typeof AdminLupgPresentationIndexRoute
  '/admin/lupg/programs': typeof AdminLupgProgramsIndexRoute
  '/admin/lupg/recap': typeof AdminLupgRecapIndexRoute
  '/admin/lupg/reports': typeof AdminLupgReportsIndexRoute
  '/admin/lupg/sensus': typeof AdminLupgSensusIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/lupg': typeof AdminLupgRouteRouteWithChildren
  '/admin/settings': typeof AdminSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/absensi/$formId': typeof AbsensiFormIdRoute
  '/admin/403': typeof Admin403Route
  '/admin/dashboard': typeof AdminDashboardRoute
  '/register/add-participant': typeof RegisterAddParticipantRoute
  '/admin/errors/$error': typeof AdminErrorsErrorRoute
  '/admin/forms/create': typeof AdminFormsCreateRoute
  '/admin/lupg/dashboard': typeof AdminLupgDashboardRoute
  '/admin/settings/account': typeof AdminSettingsAccountRoute
  '/admin/settings/appearance': typeof AdminSettingsAppearanceRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/admin/approvals/': typeof AdminApprovalsIndexRoute
  '/admin/apps/': typeof AdminAppsIndexRoute
  '/admin/attendance/': typeof AdminAttendanceIndexRoute
  '/admin/chats/': typeof AdminChatsIndexRoute
  '/admin/forms/': typeof AdminFormsIndexRoute
  '/admin/help-center/': typeof AdminHelpCenterIndexRoute
  '/admin/manage-role/': typeof AdminManageRoleIndexRoute
  '/admin/participants/': typeof AdminParticipantsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/tasks/': typeof AdminTasksIndexRoute
  '/admin/lupg/recap/present': typeof AdminLupgRecapPresentRoute
  '/admin/lupg/reports/$monthlyReportId': typeof AdminLupgReportsMonthlyReportIdRoute
  '/admin/lupg/config/': typeof AdminLupgConfigIndexRoute
  '/admin/lupg/mustin/': typeof AdminLupgMustinIndexRoute
  '/admin/lupg/presentation/': typeof AdminLupgPresentationIndexRoute
  '/admin/lupg/programs/': typeof AdminLupgProgramsIndexRoute
  '/admin/lupg/recap/': typeof AdminLupgRecapIndexRoute
  '/admin/lupg/reports/': typeof AdminLupgReportsIndexRoute
  '/admin/lupg/sensus/': typeof AdminLupgSensusIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/lupg'
    | '/admin/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/absensi/$formId'
    | '/admin/403'
    | '/admin/dashboard'
    | '/register/add-participant'
    | '/admin/errors/$error'
    | '/admin/forms/create'
    | '/admin/lupg/dashboard'
    | '/admin/settings/account'
    | '/admin/settings/appearance'
    | '/admin/settings/notifications'
    | '/admin/approvals'
    | '/admin/apps'
    | '/admin/attendance'
    | '/admin/chats'
    | '/admin/forms'
    | '/admin/help-center'
    | '/admin/manage-role'
    | '/admin/participants'
    | '/admin/settings/'
    | '/admin/tasks'
    | '/admin/lupg/recap/present'
    | '/admin/lupg/reports/$monthlyReportId'
    | '/admin/lupg/config'
    | '/admin/lupg/mustin'
    | '/admin/lupg/presentation'
    | '/admin/lupg/programs'
    | '/admin/lupg/recap'
    | '/admin/lupg/reports'
    | '/admin/lupg/sensus'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/lupg'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/absensi/$formId'
    | '/admin/403'
    | '/admin/dashboard'
    | '/register/add-participant'
    | '/admin/errors/$error'
    | '/admin/forms/create'
    | '/admin/lupg/dashboard'
    | '/admin/settings/account'
    | '/admin/settings/appearance'
    | '/admin/settings/notifications'
    | '/admin/approvals'
    | '/admin/apps'
    | '/admin/attendance'
    | '/admin/chats'
    | '/admin/forms'
    | '/admin/help-center'
    | '/admin/manage-role'
    | '/admin/participants'
    | '/admin/settings'
    | '/admin/tasks'
    | '/admin/lupg/recap/present'
    | '/admin/lupg/reports/$monthlyReportId'
    | '/admin/lupg/config'
    | '/admin/lupg/mustin'
    | '/admin/lupg/presentation'
    | '/admin/lupg/programs'
    | '/admin/lupg/recap'
    | '/admin/lupg/reports'
    | '/admin/lupg/sensus'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/lupg'
    | '/admin/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/absensi/$formId'
    | '/admin/403'
    | '/admin/dashboard'
    | '/register/add-participant'
    | '/admin/errors/$error'
    | '/admin/forms/create'
    | '/admin/lupg/dashboard'
    | '/admin/settings/account'
    | '/admin/settings/appearance'
    | '/admin/settings/notifications'
    | '/admin/approvals/'
    | '/admin/apps/'
    | '/admin/attendance/'
    | '/admin/chats/'
    | '/admin/forms/'
    | '/admin/help-center/'
    | '/admin/manage-role/'
    | '/admin/participants/'
    | '/admin/settings/'
    | '/admin/tasks/'
    | '/admin/lupg/recap/present'
    | '/admin/lupg/reports/$monthlyReportId'
    | '/admin/lupg/config/'
    | '/admin/lupg/mustin/'
    | '/admin/lupg/presentation/'
    | '/admin/lupg/programs/'
    | '/admin/lupg/recap/'
    | '/admin/lupg/reports/'
    | '/admin/lupg/sensus/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  AbsensiFormIdRoute: typeof AbsensiFormIdRoute
  RegisterAddParticipantRoute: typeof RegisterAddParticipantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/add-participant': {
      id: '/register/add-participant'
      path: '/register/add-participant'
      fullPath: '/register/add-participant'
      preLoaderRoute: typeof RegisterAddParticipantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/403': {
      id: '/admin/403'
      path: '/403'
      fullPath: '/admin/403'
      preLoaderRoute: typeof Admin403RouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/absensi/$formId': {
      id: '/absensi/$formId'
      path: '/absensi/$formId'
      fullPath: '/absensi/$formId'
      preLoaderRoute: typeof AbsensiFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/lupg': {
      id: '/admin/lupg'
      path: '/lupg'
      fullPath: '/admin/lupg'
      preLoaderRoute: typeof AdminLupgRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tasks/': {
      id: '/admin/tasks/'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminTasksIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/participants/': {
      id: '/admin/participants/'
      path: '/participants'
      fullPath: '/admin/participants'
      preLoaderRoute: typeof AdminParticipantsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/manage-role/': {
      id: '/admin/manage-role/'
      path: '/manage-role'
      fullPath: '/admin/manage-role'
      preLoaderRoute: typeof AdminManageRoleIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/help-center/': {
      id: '/admin/help-center/'
      path: '/help-center'
      fullPath: '/admin/help-center'
      preLoaderRoute: typeof AdminHelpCenterIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/forms/': {
      id: '/admin/forms/'
      path: '/forms'
      fullPath: '/admin/forms'
      preLoaderRoute: typeof AdminFormsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/chats/': {
      id: '/admin/chats/'
      path: '/chats'
      fullPath: '/admin/chats'
      preLoaderRoute: typeof AdminChatsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/attendance/': {
      id: '/admin/attendance/'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/apps/': {
      id: '/admin/apps/'
      path: '/apps'
      fullPath: '/admin/apps'
      preLoaderRoute: typeof AdminAppsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/approvals/': {
      id: '/admin/approvals/'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/notifications': {
      id: '/admin/settings/notifications'
      path: '/notifications'
      fullPath: '/admin/settings/notifications'
      preLoaderRoute: typeof AdminSettingsNotificationsRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/appearance': {
      id: '/admin/settings/appearance'
      path: '/appearance'
      fullPath: '/admin/settings/appearance'
      preLoaderRoute: typeof AdminSettingsAppearanceRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/settings/account': {
      id: '/admin/settings/account'
      path: '/account'
      fullPath: '/admin/settings/account'
      preLoaderRoute: typeof AdminSettingsAccountRouteImport
      parentRoute: typeof AdminSettingsRouteRoute
    }
    '/admin/lupg/dashboard': {
      id: '/admin/lupg/dashboard'
      path: '/dashboard'
      fullPath: '/admin/lupg/dashboard'
      preLoaderRoute: typeof AdminLupgDashboardRouteImport
      parentRoute: typeof AdminLupgRouteRoute
    }
    '/admin/forms/create': {
      id: '/admin/forms/create'
      path: '/forms/create'
      fullPath: '/admin/forms/create'
      preLoaderRoute: typeof AdminFormsCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/errors/$error': {
      id: '/admin/errors/$error'
      path: '/errors/$error'
      fullPath: '/admin/errors/$error'
      preLoaderRoute: typeof AdminErrorsErrorRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/lupg/sensus/': {
      id: '/admin/lupg/sensus/'
      path: '/sensus'
      fullPath: '/admin/lupg/sensus'
      preLoaderRoute: typeof AdminLupgSensusIndexRouteImport
      parentRoute: typeof AdminLupgRouteRoute
    }
    '/admin/lupg/reports/': {
      id: '/admin/lupg/reports/'
      path: '/reports'
      fullPath: '/admin/lupg/reports'
      preLoaderRoute: typeof AdminLupgReportsIndexRouteImport
      parentRoute: typeof AdminLupgRouteRoute
    }
    '/admin/lupg/recap/': {
      id: '/admin/lupg/recap/'
      path: '/recap'
      fullPath: '/admin/lupg/recap'
      preLoaderRoute: typeof AdminLupgRecapIndexRouteImport
      parentRoute: typeof AdminLupgRouteRoute
    }
    '/admin/lupg/programs/': {
      id: '/admin/lupg/programs/'
      path: '/programs'
      fullPath: '/admin/lupg/programs'
      preLoaderRoute: typeof AdminLupgProgramsIndexRouteImport
      parentRoute: typeof AdminLupgRouteRoute
    }
    '/admin/lupg/presentation/': {
      id: '/admin/lupg/presentation/'
      path: '/presentation'
      fullPath: '/admin/lupg/presentation'
      preLoaderRoute: typeof AdminLupgPresentationIndexRouteImport
      parentRoute: typeof AdminLupgRouteRoute
    }
    '/admin/lupg/mustin/': {
      id: '/admin/lupg/mustin/'
      path: '/mustin'
      fullPath: '/admin/lupg/mustin'
      preLoaderRoute: typeof AdminLupgMustinIndexRouteImport
      parentRoute: typeof AdminLupgRouteRoute
    }
    '/admin/lupg/config/': {
      id: '/admin/lupg/config/'
      path: '/config'
      fullPath: '/admin/lupg/config'
      preLoaderRoute: typeof AdminLupgConfigIndexRouteImport
      parentRoute: typeof AdminLupgRouteRoute
    }
    '/admin/lupg/reports/$monthlyReportId': {
      id: '/admin/lupg/reports/$monthlyReportId'
      path: '/reports/$monthlyReportId'
      fullPath: '/admin/lupg/reports/$monthlyReportId'
      preLoaderRoute: typeof AdminLupgReportsMonthlyReportIdRouteImport
      parentRoute: typeof AdminLupgRouteRoute
    }
    '/admin/lupg/recap/present': {
      id: '/admin/lupg/recap/present'
      path: '/recap/present'
      fullPath: '/admin/lupg/recap/present'
      preLoaderRoute: typeof AdminLupgRecapPresentRouteImport
      parentRoute: typeof AdminLupgRouteRoute
    }
  }
}

interface AdminLupgRouteRouteChildren {
  AdminLupgDashboardRoute: typeof AdminLupgDashboardRoute
  AdminLupgRecapPresentRoute: typeof AdminLupgRecapPresentRoute
  AdminLupgReportsMonthlyReportIdRoute: typeof AdminLupgReportsMonthlyReportIdRoute
  AdminLupgConfigIndexRoute: typeof AdminLupgConfigIndexRoute
  AdminLupgMustinIndexRoute: typeof AdminLupgMustinIndexRoute
  AdminLupgPresentationIndexRoute: typeof AdminLupgPresentationIndexRoute
  AdminLupgProgramsIndexRoute: typeof AdminLupgProgramsIndexRoute
  AdminLupgRecapIndexRoute: typeof AdminLupgRecapIndexRoute
  AdminLupgReportsIndexRoute: typeof AdminLupgReportsIndexRoute
  AdminLupgSensusIndexRoute: typeof AdminLupgSensusIndexRoute
}

const AdminLupgRouteRouteChildren: AdminLupgRouteRouteChildren = {
  AdminLupgDashboardRoute: AdminLupgDashboardRoute,
  AdminLupgRecapPresentRoute: AdminLupgRecapPresentRoute,
  AdminLupgReportsMonthlyReportIdRoute: AdminLupgReportsMonthlyReportIdRoute,
  AdminLupgConfigIndexRoute: AdminLupgConfigIndexRoute,
  AdminLupgMustinIndexRoute: AdminLupgMustinIndexRoute,
  AdminLupgPresentationIndexRoute: AdminLupgPresentationIndexRoute,
  AdminLupgProgramsIndexRoute: AdminLupgProgramsIndexRoute,
  AdminLupgRecapIndexRoute: AdminLupgRecapIndexRoute,
  AdminLupgReportsIndexRoute: AdminLupgReportsIndexRoute,
  AdminLupgSensusIndexRoute: AdminLupgSensusIndexRoute,
}

const AdminLupgRouteRouteWithChildren = AdminLupgRouteRoute._addFileChildren(
  AdminLupgRouteRouteChildren,
)

interface AdminSettingsRouteRouteChildren {
  AdminSettingsAccountRoute: typeof AdminSettingsAccountRoute
  AdminSettingsAppearanceRoute: typeof AdminSettingsAppearanceRoute
  AdminSettingsNotificationsRoute: typeof AdminSettingsNotificationsRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
}

const AdminSettingsRouteRouteChildren: AdminSettingsRouteRouteChildren = {
  AdminSettingsAccountRoute: AdminSettingsAccountRoute,
  AdminSettingsAppearanceRoute: AdminSettingsAppearanceRoute,
  AdminSettingsNotificationsRoute: AdminSettingsNotificationsRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
}

const AdminSettingsRouteRouteWithChildren =
  AdminSettingsRouteRoute._addFileChildren(AdminSettingsRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminLupgRouteRoute: typeof AdminLupgRouteRouteWithChildren
  AdminSettingsRouteRoute: typeof AdminSettingsRouteRouteWithChildren
  Admin403Route: typeof Admin403Route
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminErrorsErrorRoute: typeof AdminErrorsErrorRoute
  AdminFormsCreateRoute: typeof AdminFormsCreateRoute
  AdminApprovalsIndexRoute: typeof AdminApprovalsIndexRoute
  AdminAppsIndexRoute: typeof AdminAppsIndexRoute
  AdminAttendanceIndexRoute: typeof AdminAttendanceIndexRoute
  AdminChatsIndexRoute: typeof AdminChatsIndexRoute
  AdminFormsIndexRoute: typeof AdminFormsIndexRoute
  AdminHelpCenterIndexRoute: typeof AdminHelpCenterIndexRoute
  AdminManageRoleIndexRoute: typeof AdminManageRoleIndexRoute
  AdminParticipantsIndexRoute: typeof AdminParticipantsIndexRoute
  AdminTasksIndexRoute: typeof AdminTasksIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminLupgRouteRoute: AdminLupgRouteRouteWithChildren,
  AdminSettingsRouteRoute: AdminSettingsRouteRouteWithChildren,
  Admin403Route: Admin403Route,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminErrorsErrorRoute: AdminErrorsErrorRoute,
  AdminFormsCreateRoute: AdminFormsCreateRoute,
  AdminApprovalsIndexRoute: AdminApprovalsIndexRoute,
  AdminAppsIndexRoute: AdminAppsIndexRoute,
  AdminAttendanceIndexRoute: AdminAttendanceIndexRoute,
  AdminChatsIndexRoute: AdminChatsIndexRoute,
  AdminFormsIndexRoute: AdminFormsIndexRoute,
  AdminHelpCenterIndexRoute: AdminHelpCenterIndexRoute,
  AdminManageRoleIndexRoute: AdminManageRoleIndexRoute,
  AdminParticipantsIndexRoute: AdminParticipantsIndexRoute,
  AdminTasksIndexRoute: AdminTasksIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  AbsensiFormIdRoute: AbsensiFormIdRoute,
  RegisterAddParticipantRoute: RegisterAddParticipantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
